on: [push]

jobs:
  run_tests_job:
    runs-on: ubuntu-latest
    name: commit gate (tests)
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run testcases
        uses: ./.github/actions/run-tests
        id: run-tests

  build_model_job:
    runs-on: ubuntu-latest
    name: commit gate (build)
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build model
        uses: ./.github/actions/build-model
        id: build-model
